Repository livewire/livewire, pull requests merged in 2019-12, with the labels that each got.

#430 Use Turbolinks when available
  src/js/Component/index.js
Labels: Type: Bug

#429 Resolve ComponentNotFoundException when Manifest is Out of Date
  src/LivewireManager.php
  tests/DiscoverCommandTest.php
Labels: Type: Enhancement

#414 support eloquent models for the fill method
  composer.json
  src/ComponentConcerns/InteractsWithProperties.php
  tests/ComponentCanBeFilledTest.php
Labels: Type: Enhancement

#385 Make Livewire compatible with Laravel Vapor
  .gitignore
  config/livewire.php
  src/LivewireServiceProvider.php
Labels: Type: Enhancement

#497 Comment to run livewire:discover when namespace changes
  config/livewire.php
Labels: Type: Maintenance

#493 add assertNotFound, assertForbidden and assertUnauthorized assertions
  composer.json
  src/Testing/Concerns/MakesAssertions.php
  src/Testing/Concerns/MakesCallsToComponent.php
  src/Testing/TestableLivewire.php
  tests/TestableLivewireCanAssertStatusCodes.php
Labels: Type: Enhancement
