Repository livewire/livewire, pull requests merged in 2020-06, with the labels that each got.

#999 Allow expressions in action params
  dist/livewire.js
  dist/livewire.js.map
  dist/manifest.json
  js/dom/directive.js
  tests/js/event_actions.spec.js
Labels: Type: Enhancement

#980 Fix Testing Livewire Route Conflict
  src/Testing/TestableLivewire.php
  tests/TestableLivewireTestingLivewireRouteTest.php
Labels: Type: Maintenance

#958 Support file uploads
  .github/workflows/test.yml
  config/livewire.php
  dist/livewire.js
  dist/livewire.js.map
  js/component/FileUploads.js
  js/component/LoadingStates.js
  js/component/UploadManager.js
  js/component/index.js
  js/connection/drivers/http.js
  js/dom/dom_element.js
  js/index.js
  js/node_initializer.js
  js/util/getCsrfToken.js
  js/util/index.js
  src/Commands/S3CleanupCommand.php
  src/ComponentConcerns/HandlesActions.php
  src/ComponentConcerns/InteractsWithProperties.php
  src/Controllers/CanPretendToBeAFile.php
  src/Controllers/FilePreviewHandler.php
  src/Controllers/FileUploadHandler.php
  src/Controllers/HttpConnectionHandler.php
  src/Controllers/LivewireJavaScriptAssets.php
  src/Exceptions/MissingFileUploadsTraitException.php
  src/Exceptions/S3DoesntSupportMultipleFileUploads.php
  src/FileUploadConfiguration.php
  src/GenerateSignedUploadUrl.php
  src/HydrationMiddleware/HydratePropertiesWithCustomRuntimeHydrators.php
  src/LivewireServiceProvider.php
  src/TemporarilyUploadedFile.php
  src/Testing/Concerns/MakesCallsToComponent.php
  src/Testing/TestableLivewire.php
  src/WithFileUploads.php
  tests/FileUploadsTest.php
Labels: Type: Enhancement

#969 Fix checkbox custom value always boolean
  js/dom/dom_element.js
Labels: Type: Bug

#1045 test: avoid test contamination in lifecycle hooks
  tests/LifecycleHooksTest.php
Labels: Type: Maintenance

#1009 feat: call 'updating' and 'updated' for $set and $toggle
  src/ComponentConcerns/HandlesActions.php
  tests/LifecycleHooksTest.php
Labels: Type: Enhancement

#997 [PHP] Resolve default value if given value is null
  src/ComponentConcerns/HandlesActions.php
  tests/ComponentDependencyInjectionTest.php
Labels: Type: Bug

#961 Fix #953 Emit function on the tests
  src/Testing/Concerns/MakesCallsToComponent.php
  tests/TestableLiveWireEmitEventsTest.php
Labels: Type: Bug

#1072 Format the file upload rules as an array
  config/livewire.php
  src/Controllers/FileUploadHandler.php
  src/FileUploadConfiguration.php
Labels: Type: Maintenance

#1100 Fixed a typo which was causing filesystem default driver recognition …
  src/FileUploadConfiguration.php
Labels: Type: Bug

#1099 created a fix for sorted/associative eloquent collections which cause…
  src/Component.php
  tests/ModelsCanBeSetAsPublicPropertiesTest.php
Labels: Type: Bug

#1097 Bump github workflow version
  .github/workflows/test.yml
Labels: Type: Maintenance

#1119 [Fix]: File Uploads - Removing first value in the array no longer res…
  src/WithFileUploads.php
  tests/FileUploadsTest.php
Labels: Needs Test
