Repository livewire/livewire, pull requests merged in 2020-02, with the labels that each got.

#571 [JS] wire:click paramters
  dist/livewire.js
  dist/livewire.js.map
  dist/manifest.json
  js/dom/directive.js
  tests/js/event_actions.spec.js
Labels: Type: Bug

#596 added jest tests to github actions
  .github/workflows/test.yml
Labels: Type: Maintenance

#642 Fixes JS so it doesn't break when minified in production
  src/LivewireManager.php
Labels: Type: Maintenance

#635 [PHP] added test to ensure livewire routes are cachable
  tests/CacheRoutesTest.php
Labels: Type: Maintenance

#628 spelling error
  tests/ComponentsAreSecureTest.php
Labels: Type: Maintenance

#620 Fix Issue #612
  src/CompilerEngine.php
Labels: Type: Bug

#619 Update the property not found exception message to include the component name
  src/Component.php
Labels: Type: Maintenance

#616 feat: Added wire:loading.remove directive
  dist/livewire.js
  dist/livewire.js.map
  js/component/LoadingStates.js
  tests/js/loading_states.spec.js
Labels: Type: Enhancement

#570 Implement an Echo Manager
  dist/livewire.js
  dist/livewire.js.map
  dist/manifest.json
  js/component/EchoManager.js
  js/component/index.js
Labels: Type: Maintenance
