Repository livewire/livewire, pull requests merged in 2020-03, with the labels that each got.

#651 Fix operating system discrimination
  src/Commands/FileManipulationCommand.php
Labels: Type: Maintenance

#586 [JS] Fix broken IE11 support by transpiling spread syntax using babel
  babel.config.js
  dist/livewire.js
  dist/livewire.js.map
  dist/manifest.json
  package-lock.json
  package.json
Labels: Type: Bug

#646 Flash Livewire validation errors to session like Laravel validations do
  src/Component.php
  tests/ValidationTest.php
  tests/views/dump-errors.blade.php
Labels: Type: Bug

#686 Fix multiple error modal opening issue on server error
  js/connection/drivers/http.js
Labels: Type: Bug

#681 Fix string representation display of directories
  src/Commands/ComponentParser.php
Labels: Type: Maintenance

#680 [Tests] Both slashes are valid directory separators for Windows
  tests/FileManipulationCommandParserTest.php
Labels: Type: Maintenance

#710 Fix Error Sharing
  src/Component.php
  tests/ValidationTest.php
  tests/views/dump-errors-nested-component.blade.php
  tests/views/dump-errors.blade.php
Labels: Type: Bug

#709 Allow an empty literal string value when using tag-syntax
  src/LivewireTagCompiler.php
  tests/ComponentCanAcceptValuesTest.php
  tests/views/pass-values.blade.php
Labels: Type: Bug

#706 Automatically convert Snake case naming convention
  src/Commands/ComponentParser.php
  tests/MakeCommandTest.php
Labels: Type: Bug

#703 Enhance IDE support
  src/Livewire.php
Labels: Type: Maintenance

#702 Updated default asset URL in configuration file
  config/livewire.php
Labels: Type: Enhancement

#695 ALSO disable selects and textareas on form submit.
  dist/livewire.js
  dist/livewire.js.map
  dist/manifest.json
  js/component/DisableForms.js
  tests/js/event_actions.spec.js
Labels: Type: Enhancement

#720 remove vue support
  dist/livewire.js
  dist/livewire.js.map
  dist/manifest.json
  js/component/SupportVueJs.js
  js/index.js
Labels: Type: Enhancement

#718 Allow empty value (using single quotes) to be passed
  src/LivewireTagCompiler.php
Labels: Type: Maintenance

#719 add beforeElementUpdate and elementUpdated hook
  dist/livewire.js
  dist/livewire.js.map
  js/HookManager.js
  js/component/index.js
Labels: Type: Maintenance

#683 [PHP] support fqcn for SPA routes
  README.md
  src/LivewireManager.php
  tests/RouteRegistrationTest.php
  tests/RouterMacrosTest.php
Labels: Type: Enhancement

#768 Update Redirector.php
  src/Redirector.php
Labels: Type: Bug

#743 Use config file class namespace to resolve Livewire folder path
  src/Commands/FileManipulationCommand.php
Labels: Type: Maintenance
