Repository livewire/livewire, pull requests merged in 2020-01, with the labels that each got.

#504 SyncHooks for nested arrays
  src/ComponentConcerns/HandlesActions.php
  tests/LifecycleHooksTest.php
  tests/ModelsCanBeSetAsPublicPropertiesTest.php
Labels: Type: Bug

#511 #506 component-classname-blade-directive-callable
  src/LivewireManager.php
  tests/LivewireDirectivesTest.php
Labels: Type: Enhancement

#512 Add system modifier keys
  dist/livewire.js
  dist/livewire.min.js
  dist/mix-manifest.json
  src/js/node_initializer.js
  tests/js/event_actions.spec.js
Labels: Type: Enhancement

#516 Make public properties available to view again
  src/Component.php
  tests/PublicPropertiesAreAvailableInTheViewTest.php
Labels: Type: Enhancement

#521 fix vapor condition
  src/LivewireServiceProvider.php
Labels: Type: Bug

#524 Support published assets on Laravel Vapor
  src/LivewireManager.php
Labels: Type: Bug

#525 Make it compatible with PHP 7.1
  src/LivewireServiceProvider.php
Labels: Type: Maintenance

#529 Refactor polyfills and update IE support
  dist/livewire.js
  dist/livewire.min.js
  dist/mix-manifest.json
  package-lock.json
  package.json
  src/js/dom/polyfills.js
  src/js/dom/polyfills/index.js
  src/js/dom/polyfills/modules/es.element.closest.js
  src/js/dom/polyfills/modules/es.element.get-attribute-names.js
  src/js/dom/polyfills/modules/es.element.matches.js
  src/js/index.js
Labels: Type: Enhancement

#536 Fix matrix build and Laravel 7 support
  .github/workflows/test.yml
  composer.json
  src/Commands/ComponentParser.php
  src/Commands/FileManipulationCommand.php
  src/CompilerEngine.php
  src/DataCaster.php
  src/LivewireServiceProvider.php
  src/LivewireViewCompilerEngine.php
  src/Testing/Concerns/MakesAssertions.php
  tests/CopyCommandTest.php
  tests/DeleteCommandTest.php
  tests/DiscoverCommandTest.php
  tests/LivewireDirectivesTest.php
  tests/MakeCommandTest.php
  tests/MoveCommandTest.php
  tests/StubCommandTest.php
  tests/TestableLivewireCanAssertStatusCodesTest.php
Labels: Type: Enhancement

#562 make pagination responsive
  src/views/pagination-links.blade.php
Labels: Type: Enhancement

#548 [JS] rename component directory to lower-case
  dist/livewire.js.map
  src/js/component/DirtyStates.js
  src/js/component/DisableForms.js
  src/js/component/LoadingStates.js
  src/js/component/OfflineStates.js
  src/js/component/Polling.js
  src/js/component/PrefetchManager.js
  src/js/component/SupportVueJs.js
  src/js/component/UpdateQueryString.js
  src/js/component/index.js
  src/js/index.js
Labels: Type: Bug

#551 [JS] parameter parsing
  dist/livewire.js
  dist/livewire.js.map
  dist/manifest.json
  src/js/dom/directive.js
  tests/js/event_actions.spec.js
Labels: Type: Bug

#556 fix error assertion check on undefined index
  src/Testing/Concerns/MakesAssertions.php
Labels: Type: Bug
