Repository livewire/livewire, pull requests merged in 2020-05, with the labels that each got.

#861 Reorder polyfil
  dist/livewire.js
  dist/livewire.js.map
  dist/manifest.json
  js/index.js
Labels: Type: Maintenance

#867 Added MIT License File
  LICENSE.md
  README.md
Labels: Type: Maintenance

#886 Fix #875 wire:loading.class=" " & wire:loading.remove.class=" "
  dist/livewire.js
  dist/livewire.js.map
  dist/manifest.json
  js/component/LoadingStates.js
  tests/js/loading_states.spec.js
Labels: Type: Bug

#889 #888 fix notice missing BladeComplier
  src/LivewireServiceProvider.php
Labels: Type: Bug

#894 Add deeply nested array support to validateOnly method
  src/ComponentConcerns/ValidatesInput.php
  tests/ValidationTest.php
Labels: Type: Enhancement

#915 Adds forward slash nested component names to livewire:make command
  src/Commands/ComponentParser.php
  src/Commands/StubParser.php
  tests/MakeCommandTest.php
Labels: Type: Bug

#912 add assertSeeHtml
  src/Testing/Concerns/MakesAssertions.php
  tests/LivewireTestingTest.php
  tests/views/show-html.blade.php
Labels: Type: Enhancement

#924 [PHP] Dedicated test to cover current DI implementation
  tests/ComponentDependencyInjectionTest.php
  tests/DataBindingTest.php
Labels: Type: Maintenance

#945 Improve issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Type: Maintenance

#927 add assertNotEmitted
  src/Testing/Concerns/MakesAssertions.php
  tests/LivewireTestingTest.php
Labels: Type: Maintenance

#939 Add ->only() method to components
  src/ComponentConcerns/InteractsWithProperties.php
  tests/ComponentCanReturnOnlySpecifiedPropertiesTest.php
Labels: Type: Enhancement

#944 Link to Discord server
  README.md
Labels: Type: Maintenance

#946 Missing root tag exception
  src/Exceptions/RootTagMissingFromViewException.php
  src/HydrationMiddleware/AddAttributesToRootTagOfHtml.php
  src/HydrationMiddleware/IncludeIdAsRootTagAttribute.php
  src/LivewireManager.php
  tests/ComponentRootHasIdAndComponentDataTest.php
  tests/views/rootless-view.blade.php
Labels: Type: Maintenance

#947 Reset properties from array
  src/ComponentConcerns/InteractsWithProperties.php
  tests/ResetPropertiesTest.php
Labels: Type: Maintenance

#949 Fix typo in method name
  src/ComponentConcerns/HandlesActions.php
Labels: Type: Maintenance

#967 Fix command descriptions not being in line with Laravel conventions
  src/Commands/CopyCommand.php
  src/Commands/DeleteCommand.php
  src/Commands/DiscoverCommand.php
  src/Commands/MakeCommand.php
  src/Commands/MoveCommand.php
  src/Commands/StubsCommand.php
Labels: Type: Maintenance
