Repository livewire/livewire, pull requests merged in 2023-08, with the labels that each got.

#6083 [v2] Fix for imageSize method on TemporaryUploadedFile to support dimensions validation rule
  src/TemporaryUploadedFile.php
Labels: Changes Requested

#6084 [v3] Fix for imageSize method on TemporaryUploadedFile to support dimensions validation rule
  src/Features/SupportFileUploads/TemporaryUploadedFile.php
Labels: Changes Requested

#6154 [v3] Small fix on understanding-nesting.md
  docs/understanding-nesting.md
Labels: Docs

#6087 [V3] Add failing test for component with wire:model and custom Alpine directive
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  src/Features/SupportModels/BrowserTest.php
Labels: Failing Test

#6166 Fail delete child test
  dist/manifest.json
  src/Features/SupportNestingComponents/BrowserTest.php
Labels: Failing Test

#6177 [V3] Add tests for modelable nested component
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  src/Features/SupportWireModelingNestedComponents/BrowserTest.php
  src/Features/SupportWireModelingNestedComponents/Modelable.php
  src/Features/SupportWireModelingNestedComponents/SupportWireModelingNestedComponents.php
Labels: Failing Test

#6194 [v3] Docs typo
  docs/javascript.md
Labels: Docs

#6233 [V3] Move auto-injected livewire styles to end of head tag
  src/Features/SupportAutoInjectedAssets/BrowserTest.php
  src/Features/SupportAutoInjectedAssets/SupportAutoInjectedAssets.php
  src/Features/SupportAutoInjectedAssets/UnitTest.php
  tests/views/layouts/app-with-styles.blade.php
Labels: Bug Fix

#6232 [V3] Add Windows PowerShell warning to docs
  docs/installation.md
  docs/quickstart.md
Labels: Docs

#6226 [V3] Docs: add example of firing a specific action while polling
  docs/polling.md
Labels: Docs

#6225 [v3] Add failing test for calling the remove upload method
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/$wire.js
  js/features/supportFileUploads.js
  src/Features/SupportFileUploads/SupportFileUploads.php
  src/Features/SupportFileUploads/UnitTest.php
  src/Features/SupportFileUploads/WithFileUploads.php
  src/Features/SupportTesting/Testable.php
Labels: Failing Test

#6201 [V3] Passing test for layout stacks #6135
  src/Features/SupportPageComponents/SupportPageComponents.php
  src/Features/SupportPageComponents/UnitTest.php
  src/Features/SupportValidation/HandlesValidation.php
  src/Mechanisms/HandleComponents/HandleComponents.php
  src/Mechanisms/HandleComponents/ViewContext.php
  tests/views/layouts/app-layout-with-stacks.blade.php
Labels: Review

#6190 [v3] Fix ArraySynth hydrate loop __rm__
  src/Mechanisms/HandleComponents/Synthesizers/ArraySynth.php
  src/Mechanisms/HandleComponents/Synthesizers/Tests/DataBindingUnitTest.php
Labels: Review, Bug Fix

#6262 [V3] Failing test for navigate back button not working when using scripts on non-livewire page
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  docs/navigate.md
  src/Features/SupportNavigate/BrowserTest.php
Labels: Failing Test

#6264 [V3] Add failing test for child events not being listened to correctly after navigate
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/component.js
  js/features/supportEvents.js
  js/store.js
  src/Features/SupportNavigate/BrowserTest.php
Labels: Failing Test

#5920 [v3] Add failing tests for updating typed properties
  src/Mechanisms/HandleComponents/BrowserTest.php
  src/Mechanisms/HandleComponents/HandleComponents.php
  src/Mechanisms/HandleComponents/UnitTest.php
Labels: Failing Test

#6180 [v3] add failing test for nested reactive property
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/features/supportProps.js
  src/Features/SupportReactiveProps/BrowserTest.php
Labels: Failing Test

#6299 [v3] Use the actual wrapper element type when wrapping HTML during morph
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/morph.js
  src/Tests/UpdatingTableRowsTest.php
Labels: Bug Fix

#6345 [V3] Can reset unset properties
  src/Concerns/InteractsWithProperties.php
  src/Concerns/Tests/ResetPropertiesUnitTest.php
Labels: Bug Fix

#6288 [V3] fix assertNoRedirect for plain rendering components
  src/Features/SupportRedirects/TestsRedirects.php
  src/Features/SupportTesting/Tests/TestableLivewireCanAssertNoRedirectUnitTest.php
Labels: Bug Fix

#6096 [V3] Test cleanup
  legacy_tests/Browser/Dirty/Component.php
  legacy_tests/Browser/Dirty/Test.php
  legacy_tests/Browser/Dirty/view.blade.php
  legacy_tests/Browser/Extensions/Component.php
  legacy_tests/Browser/Extensions/Test.php
  legacy_tests/Browser/Extensions/view.blade.php
  legacy_tests/Browser/FileDownloads/Component.php
  legacy_tests/Browser/FileDownloads/Test.php
  legacy_tests/Browser/FileDownloads/view.blade.php
  legacy_tests/Browser/Ignore/Component.php
  legacy_tests/Browser/Ignore/Test.php
  legacy_tests/Browser/Ignore/view.blade.php
  legacy_tests/Browser/Init/Component.php
  legacy_tests/Browser/Init/Test.php
  legacy_tests/Browser/Init/view.blade.php
  legacy_tests/Browser/MagicActions/Component.php
  legacy_tests/Browser/MagicActions/Test.php
  legacy_tests/Browser/Offline/Component.php
  legacy_tests/Browser/Offline/Test.php
  legacy_tests/Browser/Offline/view.blade.php
  legacy_tests/Browser/Polling/Component.php
  legacy_tests/Browser/Polling/Test.php
  legacy_tests/Browser/Polling/view.blade.php
  legacy_tests/Browser/ProductionTest/Component.php
  legacy_tests/Browser/ProductionTest/Test.php
  legacy_tests/Browser/SupportCollections/view.blade.php
  legacy_tests/Browser/SupportDateTimes/Component.php
  legacy_tests/Browser/SupportDateTimes/Test.php
  legacy_tests/Browser/SupportDateTimes/view.blade.php
  legacy_tests/Browser/SupportEnums/Component.php
  legacy_tests/Browser/SupportEnums/Test.php
  legacy_tests/Browser/SupportEnums/view.blade.php
  legacy_tests/Browser/SupportStringables/Component.php
  legacy_tests/Browser/SupportStringables/Test.php
  legacy_tests/Browser/SupportStringables/view.blade.php
  src/Features/SupportTesting/DuskTestable.php
Labels: Review, Chore

#6160 [v3] Add except method to form
  src/Concerns/InteractsWithProperties.php
  src/Features/SupportFormObjects/Form.php
  src/Features/SupportFormObjects/UnitTest.php
Labels: New Feature

#6353 [v3] fix: edited toggleBooleanStateDirective
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/directives/wire-loading.js
  src/Features/SupportWireLoading/BrowserTest.php
Labels: Changes Requested, Bug Fix

#6291 [v3] Update synthesizers.md
  docs/synthesizers.md
Labels: Docs

#6327 [v3] Add failing test for lazy nested components calling boot method twice
  src/Features/SupportLazyLoading/SupportLazyLoading.php
  src/Features/SupportNestingComponents/BrowserTest.php
Labels: Failing Test

#6401 [V3] Fix rendering/rendered hooks
  src/Features/SupportLifecycleHooks/SupportLifecycleHooks.php
  src/Features/SupportLifecycleHooks/TraitsUnitTest.php
  src/Features/SupportLifecycleHooks/UnitTest.php
Labels: Bug Fix

#5780 [v3] Add component lazy loading to full page components
  config/livewire.php
  docs/lazy.md
  src/Attributes/Lazy.php
  src/Features/SupportLazyLoading/BaseLazy.php
  src/Features/SupportLazyLoading/BrowserTest.php
  src/Features/SupportLazyLoading/SupportLazyLoading.php
  src/Features/SupportPageComponents/LayoutConfig.php
Labels: New Feature

#6171 [V3] Support Defer Loading
  docs/lazy.md
  src/Features/SupportLazyLoading/BrowserTest.php
  src/Features/SupportLazyLoading/SupportLazyLoading.php
Labels: New Feature, Review

#6344 [V3] Make rule aliases translatable
  docs/validation.md
  src/Features/SupportValidation/BaseRule.php
  src/Features/SupportValidation/UnitTest.php
Labels: New Feature

#6394 [V3] Add dynamic validation attributes in Form Object
  src/Features/SupportFormObjects/Form.php
  src/Features/SupportFormObjects/UnitTest.php
Labels: New Feature

#6478 [V3] Return null on IntSynth when null is passed in
  src/Mechanisms/HandleComponents/Synthesizers/IntSynth.php
  src/Mechanisms/HandleComponents/Synthesizers/Tests/IntSynthUnitTest.php
Labels: Bug Fix

#6479 [V3] Fix TemporaryUploadedFile::dimensions return type
  src/Features/SupportFileUploads/TemporaryUploadedFile.php
  src/Features/SupportFileUploads/UnitTest.php
Labels: Bug Fix

#6521 [V3] Fix: Remove $entangled components from DOM without side effects
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/$wire.js
  package-lock.json
  src/Features/SupportEntangle/BrowserTest.php
Labels: Bug Fix

#6504 [V3] Events inline scripts - docs
  docs/events.md
Labels: Docs

#6530 [V3] Docs - Add morph hooks
  docs/javascript.md
Labels: Docs

#6469 [V3] Fix pagination hooks when using kebab page name
  src/Features/SupportPagination/BrowserTest.php
  src/Features/SupportPagination/HandlesPagination.php
Labels: Bug Fix

#6532 [V3] Feature Enhancement - Pass component parameters as an argument to placeholder() method
  docs/lazy.md
  src/Features/SupportLazyLoading/BrowserTest.php
  src/Features/SupportLazyLoading/SupportLazyLoading.php
  tests/views/placeholder.blade.php
Labels: New Feature

#6581 [V3] add failing test for redirect with navigate via $parent
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/$wire.js
  src/Features/SupportNavigate/BrowserTest.php
Labels: Failing Test

#6524 [V3] Refactor redirectRoute & redirectAction
  src/Features/SupportRedirects/HandlesRedirects.php
Labels: Bug Fix

#6512 [V2] Add failing tests for `TestableLivewire`
  src/Testing/TestableLivewire.php
  tests/Unit/TestableLivewireClearsInstancesTest.php
Labels: Failing Test
