Repository livewire/livewire, pull requests merged in 2023-09, with the labels that each got.

#6466 [V3] Failing test: Slots with the same name are bubbling up
  src/Features/SupportPageComponents/SupportPageComponents.php
  src/Features/SupportPageComponents/UnitTest.php
  tests/views/components/component-with-slot.blade.php
  tests/views/show-double-header-slot.blade.php
Labels: Failing Test

#6534 [V3] Updated code in a quotation block installation.md
  docs/installation.md
Labels: Docs

#6637 [V3] Update events.md
  docs/events.md
Labels: Docs

#6646 [V3] Enhance docs on the `set()` Testable
  docs/testing.md
Labels: Docs

#6497 [V3] Refactored js/directives.js
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/directives.js
Labels: Chore

#6471 [V3] Add `assertReturned` method to test return value of a method
  docs/testing.md
  src/Features/SupportTesting/MakesAssertions.php
  src/Features/SupportTesting/UnitTest.php
Labels: New Feature

#6673 [V3] Fix keyboard enter on `<a>` tags with wire:navigate
  dist/livewire.esm.js
  dist/livewire.js
  js/plugins/navigate/links.js
  src/Features/SupportNavigate/BrowserTest.php
Labels: New Feature

#6559 Fix wireables not being able to be updated
  src/Features/SupportWireables/BrowserTest.php
  src/Features/SupportWireables/UnitTest.php
  src/Features/SupportWireables/WireableSynth.php
Labels: Bug Fix, Ready to Merge

#6729 Fix `reset()` to ensure a property initially set to `null` can be reset
  src/Concerns/InteractsWithProperties.php
  src/Concerns/Tests/ResetPropertiesUnitTest.php
Labels: Bug Fix, Ready to Merge

#6708 Fix pagination when there are nested components that don't have pagination
  src/Features/SupportPagination/BrowserTest.php
  src/Features/SupportPagination/SupportPagination.php
Labels: Bug Fix, Ready to Merge

#6770 Command enhancement for livewire:make using Laravel Prompts
  composer.json
  src/Features/SupportConsoleCommands/Commands/MakeCommand.php
Labels: New Feature

#6763 Fix morph aware statements case sensitivity
  src/Features/SupportMorphAwareIfStatement/SupportMorphAwareIfStatement.php
  src/Features/SupportMorphAwareIfStatement/UnitTest.php
Labels: Bug Fix

#6759 Fix `wire:dirty.remove` not restoring element once it is no longer dirty
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/directives/shared.js
  js/directives/wire-dirty.js
  src/Features/SupportDataBinding/BrowserTest.php
Labels: Failing Test

#6488 Add failing test when add error in mount method
  src/Features/SupportValidation/HandlesValidation.php
  src/Features/SupportValidation/UnitTest.php
  tests/views/show-errors.blade.php
Labels: Failing Test

#6564 Failing test for `$dispatch` being called twice instead of once
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/features/supportEvents.js
  src/Features/SupportEvents/BrowserTest.php
Labels: Failing Test

#6518 Fix renderless not working in event handler
  src/Features/SupportEvents/BrowserTest.php
  src/Features/SupportEvents/SupportEvents.php
Labels: Bug Fix

#6553 Fix SupportFileDownloads - Multibyte character support
  src/Features/SupportFileDownloads/SupportFileDownloads.php
  src/Features/SupportFileDownloads/UnitTest.php
Labels: Bug Fix

#6731 Fix Form Object Validation uninitialised properties.
  src/Features/SupportFormObjects/Form.php
  src/Features/SupportFormObjects/UnitTest.php
  src/Features/SupportValidation/HandlesValidation.php
Labels: Bug Fix

#6752 Only migrate php files when migrating from the old to new namespace
  src/Features/SupportConsoleCommands/Commands/Upgrade/ChangeDefaultNamespace.php
Labels: Bug Fix

#6808 Explains class attributes on Volt
  docs/volt.md
Labels: Docs

#6855 Update dependencies to match Laravel 10
  composer.json
Labels: Chore

#6873 Fix `$entangle` so it is no longer live by default
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/features/supportEntangle.js
  src/Features/SupportEntangle/BrowserTest.php
  src/Features/SupportTesting/DuskBrowserMacros.php
Labels: Bug Fix

#6822 Add support for adding cookies to tests
  docs/testing.md
  src/Features/SupportTesting/InitialRender.php
  src/Features/SupportTesting/Testable.php
  src/Features/SupportTesting/UnitTest.php
  src/LivewireManager.php
Labels: New Feature

#6728 Added validation call to form object docs
  docs/forms.md
Labels: Docs

#6843 Add option to modify full page component response
  docs/components.md
  src/Features/SupportPageComponents/HandlesPageComponents.php
  src/Features/SupportPageComponents/PageComponentConfig.php
  src/Features/SupportPageComponents/SupportPageComponents.php
  src/Features/SupportPageComponents/UnitTest.php
Labels: New Feature

#6626 Add lazy load warning to use same root element type
  docs/lazy.md
Labels: Docs

#6761 Attribute validation rules precedence
  src/Features/SupportValidation/BaseRule.php
  src/Features/SupportValidation/UnitTest.php
Labels: Failing Test

#6926 Fix: A locked property prevents updates to properties that start with the same string
  src/Features/SupportAttributes/SupportAttributes.php
  src/Features/SupportLockedProperties/UnitTest.php
Labels: Bug Fix

#6630 Add ability to customize the `wire:navigate` progress bar color
  config/livewire.php
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  docs/navigate.md
  js/plugins/navigate/bar.js
  src/Mechanisms/FrontendAssets/FrontendAssets.php
Labels: New Feature

#6549 Use the `route()` helper to get the update URI
  dist/manifest.json
  src/Livewire.php
  src/Mechanisms/HandleRequests/HandleRequests.php
  src/Mechanisms/Tests/CustomUpdateRouteBrowserTest.php
Labels: Bug Fix
