Repository livewire/livewire, pull requests merged in 2024-05, with the labels that each got.

#8392 Fix Issue where S3 Cleanup Command Overwrites Existing Rules
  src/Features/SupportConsoleCommands/Commands/S3CleanupCommand.php
Labels: Bug Fix

#8406 Add dark tailwind classes to pagination views
  src/Features/SupportPagination/views/simple-tailwind.blade.php
  src/Features/SupportPagination/views/tailwind.blade.php
Labels: New Feature

#8409 Update pagination Tailwind classes to match Laravel
  src/Features/SupportPagination/views/simple-tailwind.blade.php
  src/Features/SupportPagination/views/tailwind.blade.php
Labels: Chore
