Repository livewire/livewire, pull requests merged in 2024-03, with the labels that each got.

#8048 Fix unsetting legacy computed properties
  src/Features/SupportComputed/SupportLegacyComputedPropertySyntax.php
  src/Features/SupportComputed/UnitTest.php
  src/Mechanisms/DataStore.php
  src/helpers.php
Labels: Bug Fix

#8056 Adding Anchor as a core included plugins, minor wording tweaks
  docs/upgrading.md
Labels: Docs

#8052 Fix validating forms via `$this->validate()`
  src/Features/SupportFormObjects/UnitTest.php
  src/Features/SupportValidation/HandlesValidation.php
Labels: Bug Fix

#7972 Fix offline breaking runtime
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/livewire.min.js.map
  dist/manifest.json
  js/request/index.js
Labels: New Feature, Bug Fix

#8039 Failing test for wire:confirm where inputs remain disabled
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/livewire.min.js.map
  dist/manifest.json
  js/directives/wire-confirm.js
  js/directives/wire-wildcard.js
  js/features/supportDisablingFormsDuringRequest.js
  src/Features/SupportWireConfirm/BrowserTest.php
Labels: Failing Test

#8042 Add improved error logging for unclosed elements
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/livewire.min.js.map
  dist/manifest.json
  js/lifecycle.js
Labels: New Feature

#8090 Document BackEnum support
  docs/properties.md
Labels: Docs

#8087 Enable cookie testing on subsequent request
  src/Features/SupportTesting/SubsequentRender.php
  src/Features/SupportTesting/Testable.php
  src/Features/SupportTesting/UnitTest.php
Labels: New Feature

#8065 Add wire:target.except modifier functionality
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/livewire.min.js.map
  dist/manifest.json
  docs/loading.md
  docs/wire-loading.md
  js/directives/wire-loading.js
  src/Features/SupportWireLoading/BrowserTest.php
  src/Features/SupportWireLoading/browser_test_image.png
Labels: New Feature

#8105 Add @alpinejs/persist to npm link command in contribute guide
  docs/contribution-guide.md
Labels: Docs

#8106 Fix highlighting in blade samples
  docs/components.md
Labels: Docs

#8131 Update forms.md
  docs/forms.md
Labels: Docs

#8099 BaseUrl Attribute properties are not filled similarly when using queryString() methods
  src/Features/SupportQueryString/BaseUrl.php
  src/Features/SupportQueryString/UnitTest.php
Labels: Bug Fix

#8093 add cancelable alpine:navigate event
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/livewire.min.js.map
  dist/manifest.json
  docs/navigate.md
  js/features/supportNavigate.js
  js/plugins/navigate/history.js
  js/plugins/navigate/index.js
  src/Features/SupportNavigate/BrowserTest.php
  src/Features/SupportNavigate/HooksBrowserTest.php
Labels: New Feature

#8120 Fix file input clearing
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/livewire.min.js.map
  dist/manifest.json
  js/$wire.js
  js/features/supportFileUploads.js
  src/Features/SupportFileUploads/BrowserTest.php
Labels: Bug Fix

#8221 Update wire-loading.md
  docs/wire-loading.md
Labels: Docs

#8220 EloquentModelSynth: convert empty string to null for enum casted attributes
  src/Features/SupportLegacyModels/EloquentModelSynth.php
  src/Features/SupportLegacyModels/Tests/ModelAttributesCanBeCastUnitTest.php
Labels: Bug Fix
