Repository livewire/livewire, pull requests merged in 2024-01, with the labels that each got.

#7661 Extract fetch into function
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/plugins/navigate/fetch.js
  js/plugins/navigate/prefetch.js
Labels: Chore

#7551 Fix full page lazy components and using a custom layout using the layout attribute
  src/Features/SupportLazyLoading/SupportLazyLoading.php
  src/Features/SupportLazyLoading/UnitTest.php
  src/Features/SupportPageComponents/SupportPageComponents.php
  src/Mechanisms/HandleComponents/HandleComponents.php
  tests/views/components/layouts/custom.blade.php
Labels: Bug Fix

#7547 Remove `rel` attribute from button
  src/Features/SupportPagination/views/bootstrap.blade.php
  src/Features/SupportPagination/views/simple-bootstrap.blade.php
  src/Features/SupportPagination/views/tailwind.blade.php
Labels: Chore

#7433 Add redirectIntended
  docs/redirecting.md
  src/Features/SupportRedirects/HandlesRedirects.php
  src/Features/SupportRedirects/UnitTest.php
Labels: New Feature

#7239 Bugfix/handle rm in complex synths
  src/Mechanisms/HandleComponents/HandleComponents.php
  src/Mechanisms/HandleComponents/UnitTest.php
Labels: Bug Fix

#6995 Fix `wire:navigate` for manually triggered click events
  dist/livewire.esm.js
  dist/livewire.js
  js/plugins/navigate/links.js
  src/Features/SupportNavigate/BrowserTest.php
Labels: Bug Fix

#6990 Allow download of preview files directly from storage
  src/Drawer/Utils.php
  src/Features/SupportFileUploads/FilePreviewController.php
  src/Features/SupportFileUploads/FileUploadConfiguration.php
  src/Features/SupportFileUploads/UnitTest.php
Labels: New Feature

#7627 ReferenceError: dump is not defined when using ESM build
  js/request/index.js
Labels: Bug Fix

#7649 fix computed attribute - snake case in method name
  src/Features/SupportComputed/BaseComputed.php
  src/Features/SupportComputed/UnitTest.php
Labels: Bug Fix

#7670 Add warning about Laravel Mix
  docs/installation.md
Labels: Docs

#7424 Add 'except' support for queryString hooks
  src/Features/SupportQueryString/BrowserTest.php
  src/Features/SupportQueryString/SupportQueryString.php
Labels: Changes Requested, New Feature

#7359 Fix Hydrating Eloquent Collection With Duplicate ID's
  src/Features/SupportModels/EloquentCollectionSynth.php
  src/Features/SupportModels/UnitTest.php
Labels: Bug Fix

#7337 Add `assertNoFileDownloaded()` test method
  docs/downloads.md
  docs/testing.md
  src/Features/SupportFileDownloads/TestsFileDownloads.php
  src/Features/SupportFileDownloads/UnitTest.php
Labels: New Feature

#7550 Fix ReflectionException when getting property on stdClass object
  src/Drawer/BaseUtils.php
  src/Features/SupportStdClasses/UnitTest.php
Labels: Bug Fix

#6625 Add `nonce` to `nprogress` stylesheet
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/plugins/navigate/bar.js
  js/utils.js
  src/Mechanisms/FrontendAssets/FrontendAssets.php
  src/Mechanisms/FrontendAssets/UnitTest.php
Labels: New Feature, Bug Fix

#7548 Fix `wire:loading` target bug
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/directives/wire-loading.js
  src/Features/SupportWireLoading/BrowserTest.php
Labels: Bug Fix

#7667 Change `#[On]` attribute to support being defined at the component level
  src/Attributes/On.php
  src/Features/SupportEvents/BaseOn.php
  src/Features/SupportEvents/SupportEvents.php
  src/Features/SupportEvents/UnitTest.php
Labels: New Feature

#7693 Fix error in sample code div → form
  docs/morph.md
Labels: Docs

#7690 Add dependency injection to computed properties
  src/Features/SupportComputed/BaseComputed.php
  src/Features/SupportComputed/UnitTest.php
Labels: New Feature, Bug Fix

#7702 Update wire-model.md
  docs/wire-model.md
Labels: Docs

#7699 Update components.md
  docs/components.md
Labels: Docs

#7731 Update nesting.md
  docs/nesting.md
Labels: Docs

#7707 Fix: ReferenceError: `nonce` is not defined
  js/plugins/navigate/bar.js
Labels: Bug Fix

#7008 Simple togglable query string
  docs/pagination.md
  src/Features/SupportPagination/BrowserTest.php
  src/Features/SupportPagination/SupportPagination.php
  src/Features/SupportPagination/WithoutUrlPagination.php
  src/WithoutUrlPagination.php
Labels: New Feature

#7421 Add Enum binding support
  src/Drawer/ImplicitRouteBinding.php
  src/ImplicitlyBoundMethod.php
  src/Tests/ComponentMethodBindingsUnitTest.php
Labels: New Feature

#7644 Fix rules from component are ignored when a form object without rules is used
  src/Features/SupportFormObjects/UnitTest.php
  src/Features/SupportValidation/HandlesValidation.php
Labels: Bug Fix

#7679 consider preview_mimes config when building preview url
  src/Features/SupportFileUploads/FileNotPreviewableException.php
  src/Features/SupportFileUploads/TemporaryUploadedFile.php
  src/Features/SupportFileUploads/UnitTest.php
Labels: Bug Fix

#7684 Feature Cancel Upload
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  docs/uploads.md
  js/$wire.js
  js/features/supportFileUploads.js
  src/Features/SupportFileUploads/BrowserTest.php
  src/Features/SupportFileUploads/browser_test_image_big.jpg
  src/Features/SupportTesting/DuskTestable.php
  src/Features/SupportTesting/ShowDuskComponent.php
Labels: New Feature

#7508 Not defined functions when using @scripts tag
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/features/supportScriptsAndAssets.js
  src/Features/SupportScriptsAndAssets/BrowserTest.php
Labels: Failing Test

#6188 Add failing test for `null` values in arrays in query string
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/plugins/history/index.js
  src/Features/SupportQueryString/BaseUrl.php
  src/Features/SupportQueryString/BrowserTest.php
  src/Features/SupportScriptsAndAssets/BrowserTest.php
Labels: Failing Test

#6889 Add failing test for dependent select options
  docs/wire-model.md
  src/Features/SupportDataBinding/BrowserTest.php
Labels: Failing Test

#7145 Failing test wire:navigate with redirect
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/plugins/navigate/fetch.js
  js/plugins/navigate/index.js
  js/plugins/navigate/links.js
  js/plugins/navigate/prefetch.js
  src/Features/SupportNavigate/BrowserTest.php
Labels: Failing Test

#7671 Failing test: reordering the keys of an object with entangle
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/$wire.js
  js/component.js
  js/request/commit.js
  src/Features/SupportEntangle/BrowserTest.php
Labels: Failing Test

#7510 Update bound value from lifecycle hook
  src/Features/SupportDataBinding/BrowserTest.php
  src/LivewireManager.php
  src/Mechanisms/HandleComponents/HandleComponents.php
Labels: Failing Test

#7809 fix: use key in combination with persist
  src/Features/SupportComputed/BaseComputed.php
  src/Features/SupportComputed/UnitTest.php
Labels: Bug Fix

#7808 Fix nullable/optional enum implicit binding
  src/ImplicitlyBoundMethod.php
  src/Tests/ComponentMethodBindingsUnitTest.php
Labels: Bug Fix

#7804 Add a warning about using computed properties in Forms
  docs/computed-properties.md
Labels: Docs

#7813 destroy array key using unset when using dot com notation with except and as
  dist/livewire.esm.js
  dist/livewire.js
  dist/livewire.min.js
  dist/manifest.json
  js/plugins/history/index.js
  src/Features/SupportQueryString/BrowserTest.php
Labels: Failing Test

#7810 Prevent ClassMorphViolationException when enforceMorphMap is used
  src/Features/SupportLegacyModels/EloquentModelSynth.php
  src/Features/SupportLegacyModels/Tests/PublicPropertyHydrationAndDehydrationUnitTest.php
Labels: Bug Fix

#7827 Add failing test for query string not retaining loaded values
  src/Features/SupportQueryString/BrowserTest.php
Labels: Failing Test

#7825 Add a session prefix for uniqueness
  docs/session-properties.md
  src/Features/SupportSession/BaseSession.php
  src/Features/SupportSession/UnitTest.php
Labels: New Feature

#7846 Add event name to exception
  src/Features/SupportEvents/SupportEvents.php
Labels: Bug Fix

#7838 Add assertPropertyHasAttribute test helper
  src/Features/SupportTesting/MakesAssertions.php
  src/Features/SupportTesting/UnitTest.php
Labels: New Feature
